### ISSUE TITLE
MariaDB 사용하기

### ISSUE THREAD

**Issue by tnqls9582** [mygoodsupporter/mygoodsupporter#26]
1. DB 설치
2. Spring 연동

참고
- [Windows 10에 MariaDB 설치하기](https://offbyone.tistory.com/199)

**Comment by tnqls9582** [comment]
1.  [mariadb 10.5]( https://downloads.mariadb.org/) mariadb-10.5.11-winx64.msi
2. DB 설정
```
MARIADB_ROOT_PASSWORD: mygoodsupporter
MARIADB_USER: mygoodsupporter
MARIADB_PASSWORD: mygoodsupporter
MARIADB_DATABASE: mygoodsupporter
```
pom.xml
```xml
<properties>
    <org.mariadb.jdbc-version>2.7.2</org.mariadb.jdbc-version>
</properties>
```

**Comment by tnqls9582** [comment]
pom.xml
```xml
<properties>
    <org.mariadb.jdbc-version>2.7.2</org.mariadb.jdbc-version>
</properties>
<dependencies>
    <!-- https://mvnrepository.com/artifact/org.mariadb.jdbc/mariadb-java-client -->
    <dependency>
      <groupId>org.mariadb.jdbc</groupId>
      <artifactId>mariadb-java-client</artifactId>
      <version>${org.mariadb.jdbc-version}</version>
    </dependency>
</dependencies>
```

**Comment by tnqls9582** [comment]
root-context.xml
```xml
<bean id="dataSource" class="org.springframework.jdbc.datasource.DriverManagerDataSource">
        <property name="driverClassName" value="org.mariadb.jdbc.Driver"/>
        <property name="url" value="jdbc:mariadb://localhost:3306/mygoodsupporter"/>
        <property name="username" value="mygoodsupporter"/>
        <property name="password" value="mygoodsupporter"/>
</bean>
```

**Comment by tnqls9582** [comment]
docker-compose.yaml
```yaml
version: '3'
services:
  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mygoodsupporter
      MARIADB_USER: mygoodsupporter
      MARIADB_PASSWORD: mygoodsupporter
      MARIADB_DATABASE: mygoodsupporter
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
```
