### ISSUE TITLE
[CI/CD]travis-ci

### ISSUE THREAD

**Issue by safecorners** [mygoodsupporter/mygoodsupporter#62]
### Travis-CI
1. [Travis CI 소개 #1](https://blog.outsider.ne.kr/779)
2. [Travis CI 소개 #2](https://blog.outsider.ne.kr/780)

@Seulah-coder 
- [x] .travis.yaml
- [x] travis-ci 계정 생성 그룹 만들기
- [x] 리파지토리 연동

**Comment by safecorners** [comment]
.travis.yml
```yaml
language: java
jdk:
  - openjdk11

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

jobs:
  include:
    - stage: test
      script:
        - "./gradlew test"
    - stage: build
      script:
        - "./gradlew clean build"

stages:
  - name: test
```
